# Generated by Django 5.1.5 on 2025-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Man_category', models.CharField(max_length=100)),
                ('Female_category', models.CharField(max_length=100)),
                ('Kids_category', models.CharField(max_length=100)),
                ('Accessories_category', models.CharField(max_length=100)),
            ],
        ),
    ]
