# Generated by Django 5.1.5 on 2025-02-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_category',
            old_name='Accessories_category',
            new_name='Main_category',
        ),
        migrations.RemoveField(
            model_name='main_category',
            name='Female_category',
        ),
        migrations.RemoveField(
            model_name='main_category',
            name='Kids_category',
        ),
        migrations.RemoveField(
            model_name='main_category',
            name='Man_category',
        ),
    ]
