# Generated by Django 5.1.5 on 2025-02-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_accessories_category_main_category_main_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main_category')),
            ],
        ),
    ]
