# Generated by Django 5.1.5 on 2025-02-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='Sub_category',
        ),
        migrations.DeleteModel(
            name='Main_Category',
        ),
        migrations.DeleteModel(
            name='Sub_category',
        ),
    ]
