# Generated by Django 5.1.5 on 2025-02-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('product_price', models.CharField(max_length=100)),
                ('Sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_category')),
            ],
        ),
    ]
