# Generated by Django 5.1.5 on 2025-02-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_size_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size_filter',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
