# Generated by Django 5.1.5 on 2025-02-11 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_size_filter_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size_filter',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='size_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.size_filter'),
        ),
    ]
