# Generated by Django 5.1.5 on 2025-02-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_size_filter_product_product_size_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_filter',
            new_name='Size_filter',
        ),
        migrations.AddField(
            model_name='product',
            name='Brand_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.brand_filter'),
        ),
    ]
